### ISSUE TITLE
Suggested Quotes

### ISSUE THREAD

**Issue by Ealhwine** [bobby-b-bot/utils#1]
"I ask you, Ned, what good is it to wear a crown?" - preferably when someone mentions a crown
"The gods mock the prayers of kings and cowherds alike" - preferably whenever someone mentions prayer
"Backstabbing doesn't prepare you for a fight, and that's all the realm is now." - when someone mentions weakness
"Drink and stay quiet, the king is talking." When someone replies too quickly or with a derogatory word like bastard
"A bit of wine now and again, a girl squealing in bed, the feel of a horse between my legs? " when someone asks what's best in life.

**Comment by fzanettini** [comment]
Done! Quotes added and a few more in 4c19aa07f6fc6b581e8599a99c5e4dd4b88b998e.
