### ISSUE TITLE
Trigger words JSON objects ignored

### ISSUE THREAD

**Issue by run-as-admin** [bobby-b-bot/utils#3]
Only the first trigger word works.

Tested on bobby-b-bot

https://old.reddit.com/r/freefolk/comments/cshhht/github_bobbybbot_testing/

And on my configured bots

**Comment by fzanettini** [comment]
It seems to be a bug, I am checking this. Thank you for reporting it.

**Comment by fzanettini** [comment]
Fixed by pull #4 . I will deploy the update on production soon.
